import 'package:piano_tile/model/note.dart';

List<Note> initNotes() {
  return [
    Note(orderNumber: 0,line: 0),
    Note(orderNumber:1,line: 1),
    Note(orderNumber:2,line: 2),
    Note(orderNumber:3,line: 1),
    Note(orderNumber:4,line: 3),
    Note(orderNumber:5,line: 0),
    Note(orderNumber:6,line: 1),
    Note(orderNumber:7,line: 2),
    Note(orderNumber:8,line: 3),
    Note(orderNumber:9,line: 2),
    Note(orderNumber:10,line: 3),
    Note(orderNumber:11,line: 0),
    Note(orderNumber:12,line: 2),
    Note(orderNumber:13,line: 1),
    Note(orderNumber:14,line: 3),
    Note(orderNumber:15,line: 0),
    Note(orderNumber:16,line: 1),
    Note(orderNumber:17,line: 2),
    Note(orderNumber:18,line: 3),
    Note(orderNumber:19,line: 2),
    Note(orderNumber:20,line: 3),
    Note(orderNumber:21,line: 1),
    Note(orderNumber:22,line: 2),
    Note(orderNumber:23,line: 1),
    Note(orderNumber:24,line: 3),
    Note(orderNumber:25,line: 0),
    Note(orderNumber:26,line: 1),
    Note(orderNumber:27,line: 2),
    Note(orderNumber:28,line: 3),
    Note(orderNumber:29,line: 2),
    Note(orderNumber:30,line: 3),
    Note(orderNumber:31,line: 1),
    Note(orderNumber:32,line: 2),
    Note(orderNumber:33,line: 1),
    Note(orderNumber:34,line: 3),
    Note(orderNumber:35, line:0),
    Note(orderNumber:36,line: 1),
    Note(orderNumber:37,line: 2),
    Note(orderNumber:38,line: 3),
    Note(orderNumber:39,line: 2),
    Note(orderNumber:40,line: 3),
    Note(orderNumber:41,line: -1),
    Note(orderNumber:42,line: -1),
    Note(orderNumber:43,line: -1),
    Note(orderNumber:44,line: -1),
  ];
}